const fs=require('fs'),path=require('path'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),mock=require('./camera-mock.cjs');
const out=process.env.TEST_OUTPUT||path.join(require('os').tmpdir(),'hello-w-tests'),url=process.env.GAME_URL||'http://127.0.0.1:8789/hello-w-play/',root=new URL('../',url).href;
const checks=[],check=(name,pass,actual)=>checks.push({name,pass:!!pass,actual});
(async()=>{
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
 const page=await browser.newPage({viewport:{width:1280,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(mock);
 await page.goto(root+'#/work/hello-w');const embeds=page.locator('iframe[src*="hello-w-play"]');check('thesis directly embeds one playable demo',await embeds.count()===1);
 if(await embeds.count()) {
  const element=embeds.first();await element.scrollIntoViewIfNeeded();const frame=await (await element.elementHandle()).contentFrame();await frame.waitForSelector('#board[data-position]');
  check('embedded demo enters fresh game without field start',await frame.locator('#board').isVisible()&&!await frame.locator('#field-selection').isVisible()&&await frame.locator('#board').getAttribute('data-position')==='0,4');
  check('embed requests neither camera nor autoplay permission',!/camera|autoplay/i.test(await element.getAttribute('allow')||'')&&await frame.evaluate(()=>cameraTest.calls===0));
  const context=await element.evaluate(e=>e.parentElement.parentElement.innerText);check('embed has demonstration context',/demo|demonstration|2026.*experience|interactive.*explor/i.test(context),context);
  const body=await page.locator('#app').innerText();check('scope replaces year stat with four source-backed research themes',/4 themes\s+research themes informing the concept/i.test(body)&&!/2020\s+MFA research prototype/i.test(body)&&/2020/.test(body));
  await page.locator('.brand').focus();await page.keyboard.press('ArrowRight');check('parent keyboard does not move embedded ball',await frame.locator('#board').getAttribute('data-position')==='0,4');
  await frame.locator('#reset').focus();await page.keyboard.press('ArrowRight');check('focused iframe accepts arrow keyboard',await frame.locator('#board').getAttribute('data-position')==='1,4');
  for(const width of [1280,390,320]) {
   await page.setViewportSize({width,height:1000});const outer=await element.boundingBox(),inside=await frame.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,controls:[...document.querySelectorAll('[data-direction],#jump')].map(e=>e.getBoundingClientRect().toJSON())}));
   check(`embed ${width} responsive without horizontal overflow`,outer.x>=0&&outer.x+outer.width<=width+1&&!inside.overflow&&inside.controls.every(b=>b.x>=0&&b.right<=outer.width+1&&b.width>=24&&b.height>=24),{outer,inside});
   await element.screenshot({path:path.join(out,`embed-${width}.png`)});
  }
  await frame.evaluate(()=>{const saved=cameraTest.tracks;parent.__embeddedTracks=saved;});
  if(await frame.locator('#camera-toggle').isVisible()) {await frame.locator('#camera-toggle').click();await frame.evaluate(()=>cameraTest.pending.shift().resolve());await frame.waitForTimeout(30);}
  await page.evaluate(()=>location.hash='#/about');await page.waitForTimeout(100);check('route exit removes iframe and stops camera tracks',await page.locator('iframe[src*="hello-w-play"]').count()===0&&await page.evaluate(()=>__embeddedTracks.every(t=>t.stopped>0)));
 }
 await page.goto(url+'?embed=1');await page.waitForSelector('#board[data-position]',{state:'attached'});
 check('embed query automatically starts exploration',await page.locator('#board').isVisible()&&!await page.locator('#field-selection').isVisible());
 // Use the standalone entry when exercising a pre-feature page, to retain a meaningful missing-control Red.
 if(!await page.locator('#board').isVisible())await page.locator('#start-exploring').click();
 check('game exposes dedicated Jump button',await page.locator('#jump').count()===1);
 if(await page.locator('#jump').count()) {
  const state=()=>page.locator('#board').evaluate(e=>({position:e.dataset.position,steps:+e.dataset.steps,won:e.dataset.won==='true'}));
  const move=async d=>page.locator(`[data-direction="${d}"]`).click(),level=async n=>page.locator(`[data-level="${n}"]`).click();
  await page.evaluate(()=>{window.jumpCalls=[];const original=HelloWGame.jump;HelloWGame.jump=(s,d)=>{jumpCalls.push(d);return original(s,d);};});
  await level(1);for(const d of ['N','E','E','N'])await move(d);check('3D bridge button is exposed as an accessible button',await page.getByRole('button',{name:'Add missing bridge block',exact:true}).count()===1&&await page.getByRole('button',{name:'Add missing bridge block',exact:true}).isVisible());const canvas=page.locator('#block-scene canvas');check('3D game renders an actual canvas',await canvas.count()===1&&await canvas.isVisible());const beforeJumpImage=await canvas.count()?await canvas.screenshot():null;await page.locator('#jump').click();check('jump follows last attempted blocked arrow and crosses gap',JSON.stringify(await state())===JSON.stringify({position:'2,1',steps:4,won:false}));
  if(beforeJumpImage)check('3D scene visibly reflects completed jump',!beforeJumpImage.equals(await canvas.screenshot()));
  await page.locator('#undo').click();check('one undo reverses complete gap jump',(await state()).position==='2,3'&&(await state()).steps===3);
  await page.locator('#stage').focus();await page.keyboard.press('Space');check('Space repeats jump in the same facing direction',(await state()).position==='2,1'&&(await state()).steps===4);
  await page.locator('#reset').click();await page.locator('#jump').click();check('reset restores north facing and invalid jump is state-safe',await page.evaluate(()=>jumpCalls.at(-1)==='N')&&(await state()).position==='0,4'&&(await state()).steps===0&&/jump|land|block|hop/i.test(await page.locator('#feedback').textContent()));
  await move('E');await level(0);await page.locator('#jump').click();check('level switch restores north facing',await page.evaluate(()=>jumpCalls.at(-1)==='N'));
  await level(2);await move('E');await page.locator('#jump').click();check('sequence queues J without moving ball',await page.locator('#queue li').count()===2&&/jump/i.test(await page.locator('#queue li').last().getAttribute('aria-label'))&&(await state()).steps===0);
  await page.locator('#run').click();check('running disables live jump',await page.locator('#jump').isDisabled());await page.waitForTimeout(950);check('queued J follows prior queued direction',await page.evaluate(()=>jumpCalls.at(-1)==='E')&&(await state()).position==='1,4'&&(await state()).steps===1);
  for(const cancel of ['reset','switch']) {await level(2);await move('E');await page.locator('#jump').click();await page.locator('#run').click();await page.waitForTimeout(350);const n=await page.evaluate(()=>jumpCalls.length);if(cancel==='reset')await page.locator('#reset').click();else await level(1);await page.waitForTimeout(700);check(cancel+' cancels queued jump callback',await page.evaluate(()=>jumpCalls.length)===n&&(await state()).position==='0,4'&&(await state()).steps===0);}
  await page.locator('#ask-mentor').click();await page.locator('#question').fill('A question');await page.keyboard.press('Space');check('typing Space in mentoring does not jump',await page.locator('#question').inputValue()==='A question ');await page.locator('#close-mentor').click();
 }
 const lost=await browser.newPage({reducedMotion:'reduce'});lost.on('pageerror',e=>errors.push(e.message));await lost.goto(url+'?embed=1');await lost.locator('[data-level="1"]').click();await lost.locator('#block-scene canvas').evaluate(e=>e.getContext('webgl2').getExtension('WEBGL_lose_context').loseContext());await lost.waitForFunction(()=>!document.querySelector('#stage').classList.contains('has-3d'));await lost.locator('[data-gap]').click();check('lost WebGL context restores clickable SVG bridge',await lost.locator('[data-gap]').count()===0&&await lost.locator('#board').evaluate(e=>getComputedStyle(e).opacity==='1'));await lost.locator('#reset').click();await lost.locator('[data-gap]').focus();await lost.keyboard.press('Enter');check('SVG bridge remains keyboard-operable after reset following context loss',await lost.locator('[data-gap]').count()===0);await lost.close();
 const fallback=await browser.newPage({reducedMotion:'reduce'});fallback.on('pageerror',e=>errors.push(e.message));await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/.test(type)?null:original.call(this,type,...args);};});await fallback.goto(url+'?embed=1');await fallback.locator('[data-level="1"]').click();for(const d of ['N','E','E','N'])await fallback.locator('[data-direction="'+d+'"]').click();await fallback.locator('#jump').click();check('WebGL unavailable preserves visible SVG and complete gap jump',await fallback.locator('#board').evaluate(e=>getComputedStyle(e).opacity==='1'&&e.dataset.position==='2,1'&&e.dataset.steps==='4'));await fallback.close();
 check('no browser errors',errors.length===0,errors);await browser.close();const hashes=Object.fromEntries(["index.html","hello-w-play/game.js","hello-w-play/app.js","hello-w-play/style.css","hello-w-play/block-scene.js"].filter(f=>fs.existsSync(f)).map(f=>[f,require("crypto").createHash("sha256").update(fs.readFileSync(f)).digest("hex")]));const result={hashes,checks,failures:checks.filter(x=>!x.pass)};fs.writeFileSync(path.join(out,'jump-embed-results.json'),JSON.stringify(result,null,2));console.log(checks.length+' checks, '+result.failures.length+' failures',result.failures.map(x=>x.name));if(result.failures.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
