const fs = require('fs'), path = require('path'), crypto = require('crypto');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.PORTFOLIO_URL || 'http://127.0.0.1:8789/';
const out = process.env.TEST_OUTPUT || path.join(require('os').tmpdir(), 'line-siri-tests');
const checks = [];
const check = (name, pass, actual) => checks.push({ name, pass: !!pass, actual });
(async () => {
  fs.mkdirSync(out, { recursive: true });
  const browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_EXECUTABLE ? { executablePath: process.env.CHROMIUM_EXECUTABLE } : {}) });
  for (const width of [390, 1440]) {
    const page = await browser.newPage({ viewport: { width, height: 950 }, reducedMotion: 'reduce' });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(base + '#/');
    const card = page.locator('a[href="#/work/line"]').first();
    const cardText = await card.innerText();
    await card.scrollIntoViewIfNeeded();
    const cover = await card.locator('img').evaluate(async image => { await image.decode(); const rect = image.getBoundingClientRect(); return { src: image.getAttribute('src'), width: image.naturalWidth, height: image.naturalHeight, renderedWidth: rect.width, renderedHeight: rect.height, left: rect.left, right: rect.right }; });
    check(`${width}: dedicated Siri cover loads within viewport`, /cover_line_siri/.test(cover.src) && cover.width > 0 && cover.left >= 0 && cover.right <= width + 1, cover);
    await card.screenshot({ path: path.join(out, `line-home-card-${width}.png`) });
    check(`${width}: home card prioritizes Siri`, /Siri/i.test(cardText), cardText);
    await card.click();
    await page.waitForURL('**/#/work/line');
    await page.locator('.c-hero').waitFor();
    await page.evaluate(() => document.fonts.ready);
    const heading = await page.locator('h1').innerText();
    check(`${width}: LINE route opens Siri-led case`, /Siri/i.test(heading), heading);
    const copy = await page.locator('main').innerText();
    check(`${width}: Siri historical scope is explicit`, /2016/.test(copy) && /SiriKit/i.test(copy) && /private.*lab/i.test(copy), copy);
    const headings = await page.locator('main h2').allTextContents();
    const speakerIndex = headings.findIndex(text => /AI Speaker|CLOVA/i.test(text));
    check(`${width}: AI Speaker remains a distinct later subproject`, speakerIndex > 0, headings);
    check(`${width}: public WeChat reference is attributed`, /WeChat/i.test(copy) && /WWDC/i.test(copy) && /public|reference/i.test(copy), copy);
    check(`${width}: provisional visuals disclosed`, /reconstruct|provisional/i.test(copy), copy);
    check(`${width}: unrelated Group Call outcome excluded`, !/group\s*call|130\s*%/i.test(copy), copy);
    check(`${width}: original AI Speaker sections retained`, ['LINE AI Speaker', 'Scenarios first', 'Voice-interactive connection', 'Select Friends'].every(title => headings.some(h => h.includes(title))), headings);
    const requestLinks = await page.locator('a').evaluateAll(links => links.filter(a => /request.*(?:full|case study)|full.*study/i.test((a.textContent || '') + ' ' + (a.getAttribute('aria-label') || ''))).map(a => ({ label: a.textContent || a.getAttribute('aria-label'), href: a.getAttribute('href') })));
    check(`${width}: full study remains mailto`, requestLinks.length > 0 && requestLinks.every(link => link.href.startsWith('mailto:')), requestLinks);
    const images = await page.locator('main img').evaluateAll(async imgs => Promise.all(imgs.map(async image => { image.loading = 'eager'; try { await image.decode(); } catch {} return { src: image.getAttribute('src'), width: image.naturalWidth, height: image.naturalHeight }; })));
    check(`${width}: original four Speaker visuals retained`, ['WEB 77.png', 'WEB 80.png', 'WEB 82.png', 'WEB 83.png'].every(name => images.some(image => decodeURIComponent(image.src.split('?')[0]).endsWith(name))), images);
    check(`${width}: all case images decode`, images.length > 0 && images.every(image => image.width > 0 && image.height > 0), images);
    const geometry = await page.evaluate(() => ({ width: innerWidth, documentWidth: document.documentElement.scrollWidth, mainWidth: document.querySelector('main').scrollWidth }));
    check(`${width}: no horizontal overflow`, geometry.documentWidth <= width + 1 && geometry.mainWidth <= width + 1, geometry);
    await page.screenshot({ path: path.join(out, `line-siri-${width}.png`), fullPage: true });
    await page.goto(base + '#/');
    await page.locator('a[href="#/work/line"]').first().click();
    await page.locator('.c-hero').waitFor();
    check(`${width}: route can be reentered without error`, /Siri/i.test(await page.locator('h1').innerText()) && errors.length === 0, errors);
    await page.goto(base + '#/about');
    const aboutCopy = await page.locator('main').innerText();
    check(`${width}: About excludes Group Call outcome`, !/group\s*call|130\s*%/i.test(aboutCopy), aboutCopy);
    const lineAbout = aboutCopy.split('LINE Plus Corp.')[1]?.split('Samsung')[0] || '';
    check(`${width}: About names the private SiriKit lab scope`, /private.*lab/i.test(lineAbout) && /SiriKit/i.test(lineAbout), lineAbout);
    await page.close();
  }
  await browser.close();
  const source = fs.readFileSync(path.resolve(__dirname, '../../index.html'));
  const result = { sourceHash: crypto.createHash('sha256').update(source).digest('hex'), checks, failures: checks.filter(check => !check.pass) };
  fs.writeFileSync(path.join(out, 'line-siri-results.json'), JSON.stringify(result, null, 2));
  console.log(`${checks.length} checks, ${result.failures.length} failures`, result.failures.map(check => check.name));
  if (result.failures.length) process.exitCode = 1;
})().catch(error => { console.error(error); process.exit(1); });
