const assert=require('assert/strict'),fs=require('fs'),path=require('path');const target=process.argv[2]||path.resolve(__dirname,'../game.js'),g=require(target),checks=[];const test=(name,fn)=>{try{fn();checks.push({name,pass:true})}catch(e){checks.push({name,pass:false,error:e.message})}},same=(a,b)=>assert.deepEqual(a,b),run=(s,seq)=>seq.reduce((s,d)=>g.move(s,d),s),snap=s=>JSON.parse(JSON.stringify(s));
const output=process.env.TEST_OUTPUT || path.join(require('os').tmpdir(),'hello-w-tests');fs.mkdirSync(output,{recursive:true});
const paths=[[[0,4],[1,4],[1,3],[2,3],[2,2],[3,2],[3,1],[4,1],[4,0]],[[0,4],[0,3],[1,3],[2,3],[2,1],[3,1],[4,1],[4,0]],[[0,4],[1,4],[1,3],[2,3],[2,2],[3,2],[3,1],[4,1],[4,0]]];
test('exact three challenges exported',()=>assert.equal(g.LEVELS.length,3));for(let l=0;l<3;l++){
 test('level'+l+' fresh initial state',()=>same(g.createState(l),{level:l,position:[0,4],steps:0,history:[],bridge:false,won:false}));
 test('level'+l+' legal tiles independent contract exhaustive grid',()=>{const s=g.createState(l);for(let x=-1;x<=5;x++)for(let y=-1;y<=5;y++)assert.equal(g.isWalkable(s,x,y),paths[l].some(p=>p[0]===x&&p[1]===y),'tile '+x+','+y)});
 test('level'+l+' blocked and invalid commands preserve state',()=>{const s=g.createState(l),copy=snap(s);for(const d of ['S','W','bad','',null])same(g.move(s,d),copy);same(s,copy)});
 test('level'+l+' move immutable and one successful step',()=>{const s=g.createState(l),copy=snap(s),m=g.move(s,l===1?'N':'E');same(s,copy);same(m.position,l===1?[0,3]:[1,4]);assert.equal(m.steps,1);assert.equal(m.history.length,1);assert.equal(m.won,false)});
 test('level'+l+' empty undo safe',()=>same(g.undo(g.createState(l)),g.createState(l)));
 test('level'+l+' bridge availability restriction',()=>{const s=g.createState(l),copy=snap(s),b=g.buildBridge(s);same(s,copy);assert.equal(b.bridge,l===1);same(b.position,s.position);assert.equal(b.steps,0)});
 test('level'+l+' success only final step and winner stops',()=>{let s=g.createState(l);if(l===1)s=g.buildBridge(s);const seq=l===1?['N','E','E','N','N','E','E','N']:['E','N','E','N','E','N','E','N'];for(let i=0;i<seq.length;i++){s=g.move(s,seq[i]);assert.equal(s.won,i===7)}same(s.position,[4,0]);assert.equal(s.steps,8);for(const d of ['N','E','S','W'])same(g.move(s,d),s)});
 test('level'+l+' undo restores completion and moves, keeps bridge',()=>{let s=g.createState(l);if(l===1)s=g.buildBridge(s);s=run(s,l===1?['N','E','E','N','N','E','E','N']:['E','N','E','N','E','N','E','N']);const copy=snap(s),u=g.undo(s);same(s,copy);same(u.position,[4,1]);assert.equal(u.steps,7);assert.equal(u.won,false);assert.equal(u.bridge,l===1);for(let i=0;i<7;i++)s=g.undo(i===0?u:s);same(s.position,[0,4]);assert.equal(s.steps,0);assert.equal(s.history.length,0);assert.equal(s.bridge,l===1)});
}
test('gap cannot be crossed before bridge; same move works after',()=>{const s=run(g.createState(1),['N','E','E']);same(s.position,[2,3]);same(g.move(s,'N'),s);assert.equal(g.isWalkable(s,2,2),false);const b=g.buildBridge(s);assert.equal(g.isWalkable(b,2,2),true);same(g.move(b,'N').position,[2,2]);assert.equal(g.move(b,'N').steps,4)});
test('blocked input never adds undo record',()=>{const s=g.move(g.createState(0),'E'),b=g.move(s,'S');assert.equal(b.history.length,1);same(g.undo(b),g.createState(0))});
test('fresh states do not share nested mutable arrays',()=>{const a=g.createState(0),b=g.createState(0);a.position[0]=99;a.history.push([9,9]);same(b,g.createState(0))});
const result={target,checks,failures:checks.filter(c=>!c.pass)};const label=path.basename(target).includes('skeleton')?'state-red':'state-final';fs.writeFileSync(path.join(output,label+'-results.json'),JSON.stringify(result,null,2));console.log(checks.length+' checks, '+result.failures.length+' failures');for(const x of result.failures)console.log(x.name+': '+x.error.slice(0,180));if(result.failures.length)process.exitCode=1;
